# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FoodDelivery' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Alamofire', '~> 4.7'
  pod 'ObjectMapper', '~> 3.3'
  pod 'AlamofireObjectMapper', '~> 5.0'
  # Pods for FoodDelivery

end
