# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Sale' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
	pod 'Alamofire', '~> 4.7'
    pod 'Kingfisher', '~> 4.0'
    pod 'NYAlertViewController'
    pod 'PTPopupWebView'
    pod 'PopupDialog', '~> 0.8'
  # Pods for Sale

end
